[build]
publish = "dist"
command = "pnpm run generate"

[build.environment]
NODE_VERSION = "18"
NITRO_PRESET = "netlify"

# Handle SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Handle assets
[[headers]]
for = "/_nuxt/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
