[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "dist"
command = "pnpm run build"

# Optional: Add headers for security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
